version: '2'
services:
  agenda-app:
    image: agenda
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://agenda-postgresql:5432/agenda
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
  agenda-postgresql:
    extends:
      file: postgresql.yml
      service: agenda-postgresql
